version: '3.9'
services:
  libreoffice:
    container_name: libreoffice
    image: lscr.io/linuxserver/libreoffice:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000  # Web UI port
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${VNC_PASSWORD} # VNC password for remote access
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/documents:/documents
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.libreoffice-web-redirect.redirectscheme.scheme: https
      traefik.http.services.libreoffice.loadbalancer.server.port: 3000
      traefik.http.routers.libreoffice-local-insecure.rule: Host(`libreoffice.${LOCAL_DOMAIN}`)
      traefik.http.routers.libreoffice-local-insecure.entrypoints: web
      traefik.http.routers.libreoffice-local-insecure.service: libreoffice
      traefik.http.routers.libreoffice-local-insecure.middlewares: libreoffice-web-redirect
      traefik.http.routers.libreoffice-local.rule: Host(`libreoffice.${LOCAL_DOMAIN}`)
      traefik.http.routers.libreoffice-local.entrypoints: websecure
      traefik.http.routers.libreoffice-local.service: libreoffice
      traefik.http.routers.libreoffice-local.tls: true

networks:
  tipi_main_network:
    external: true
    name: runtipi_tipi_main_network